flir_camera:
  ros__parameters:
    ## general ROS paramters:
    # 'frame_id': 'blackfly_optical'
    'frame_id': 'blackfly_calibrated'
    ## flir parameters:
    'debug': False
    'compute_brightness': False
    'adjust_timestamp': True
    'dump_node_map': False
    # set parameters defined in blackfly_s.yaml
    'gain_auto': 'Continuous'
    'pixel_format': 'BayerRG8'
    # 'pixel_format': 'BGR8'
    'exposure_auto': 'Continuous'
    # to use a user set, do this:
    # 'user_set_selector': 'UserSet0'
    # 'user_set_load': 'Yes'
    # These are useful for GigE cameras
    # 'device_link_throughput_limit': 380000000
    # 'gev_scps_packet_size': 9000
    # PTP for GigE cameras
    # 'gev_ieee_1588': True
    # 'gev_ieee_1588_mode': 'SlaveOnly', # 'SlaveOnly',  #'Auto'
    # 'use_ieee_1588' : True
    # ---- to reduce the sensor width and shift the crop
    # 'image_width': 1408
    # 'image_height': 1080
    # 'offset_x': 16
    # 'offset_y': 0
    # 'binning_x': 1
    # 'binning_y': 1
    # 'connect_while_subscribed': True
    # 'reverse_x': True
    # 'reverse_y': True
    'frame_rate_auto': 'Off'
    'frame_rate': 10.0
    'frame_rate_enable': True
    'buffer_queue_size': 10
    'trigger_mode': 'Off'
    'chunk_mode_active': True
    'chunk_selector_frame_id': 'FrameID'
    'chunk_enable_frame_id': True
    'chunk_selector_exposure_time': 'ExposureTime'
    'chunk_enable_exposure_time': True
    'chunk_selector_gain': 'Gain'
    'chunk_enable_gain': True
    'chunk_selector_timestamp': 'Timestamp'
    'chunk_enable_timestamp': True
    'diagnostic_period': 1.0
    'diagnostic_min_freq': 39.0
    'diagnostic_max_freq': 41.0


    # 'ffmpeg_image_transport.encoding': 'hevc_nvenc',
    # 'parameter_file': parameter_file,
    # 'serial_number': [LaunchConfig('serial')],