controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: True

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # fts_broad:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

#TO IMPLEMENT CHANGES, MUST COLCON BUILD!!!!
diff_controller:
  ros__parameters:
    left_wheel_names: ["FL_wheel_j", "RL_wheel_j"]
    right_wheel_names: ["FR_wheel_j", "RR_wheel_j"]

    wheel_separation: 0.6586
    wheel_radius: 0.2159 #8.5 in
    # wheel_radius: 2.159
    # wheels_per_side: 2

    use_stamped_vel: false #maybe needed based on articulatedRobotics page
    
    #if robot_localization is used for sensor fusion, set to false
    enable_odom_tf: false #disabled now that this is an input into robot_localization ekf.
                          #shows as a publisher of /tf, but doesn't publish to topic
    
    #these initial guesses taken from ros2_control/differential controller documentation:
    # https://control.ros.org/rolling/doc/ros2_controllers/diff_drive_controller/doc/userdoc.html
    # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

#joint_broad:
#  ros__parameters:

# fts_broad:
#   ros__parameters:
#     # frame_id:
#     interface_names:
#       torque:
#         z: wheel/z