planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.10
      downsample_costmap: false
      allow_unknown: true
      minimum_turning_radius: 0.05
      reverse_penalty: 3.0
      change_penalty: 0.5
      cost_penalty: 150.0 
      non_straight_penalty: 1.2
      max_iterations: 2000000
      max_on_approach_iterations: 1000
      max_planning_time: 3.0
      motion_model_for_search: "REEDS_SHEPP"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      footprint: "[ [0.35, 0.45], [0.35, -0.45], [-0.8, -0.45], [-0.8, 0.45] ]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 5.0
        decay_model: 0
        voxel_size: 0.03
        track_unknown_space: true
        unknown_threshold: 15
        mark_threshold: 3
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.2
        mapping_mode: false
        observation_sources: points
        points:
          data_type: PointCloud2
          topic: /ouster/points
          marking: true
          clearing: true
          min_obstacle_height: 0.05
          max_obstacle_height: 1.3
          obstacle_range: 10.0
          expected_update_rate: 0.0
          observation_persistence: 0.0
          filter: "voxel"
          voxel_min_points: 3
          inf_is_valid: false
          clear_after_reading: true
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.8
        cost_scaling_factor: 1.0
      always_send_full_costmap: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      footprint: "[ [0.35, 0.45], [0.35, -0.45], [-0.8, -0.45], [-0.8, 0.45] ]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 5.0
        decay_model: 0
        voxel_size: 0.03
        track_unknown_space: true
        unknown_threshold: 15
        mark_threshold: 3
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.2
        mapping_mode: false
        observation_sources: points
        points:
          data_type: PointCloud2
          topic: /ouster/points
          marking: true
          clearing: true
          min_obstacle_height: 0.05
          max_obstacle_height: 1.3
          obstacle_range: 5.5
          expected_update_rate: 0.0
          observation_persistence: 0.0
          filter: "voxel"
          voxel_min_points: 300
          inf_is_valid: false
          clear_after_reading: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0
        inflation_radius: 0.8
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    odom_topic: /odom
    robot_base_frame: base_footprint
    navigators: ['navigate_to_pose']
    default_nav_to_pose_bt_xml: "$(find-pkg-share leap_nav)/config/compute_path_only.xml"
    default_nav_through_poses_bt_xml: "$(find-pkg-share leap_nav)/config/compute_path_only.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_recovery_node_bt_node
      - nav2_rate_controller_bt_node
      - nav2_clear_costmap_service_bt_node

# controller_server:
#   ros__parameters:
#     controller_frequency: 20.0
#     controller_plugins: ["FollowPath"]
#     FollowPath:
#       plugin: "leap_controller::Controller"
#       max_linear_vel:      0.5  # m/s
#       max_angular_vel:     0.8  # rad/s
#       lookahead_dist:      2.0  # m
#       k_p_linear:          2.0
#       k_d_linear:          0.0
#       k_p_angular:         0.03
#       k_d_angular:         -0.01
#       approach_dist:       1.0  # m
#       transform_tolerance: 0.5  # s

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    use_sim_time: False
    controller_plugins: ["FollowPath"]
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.1
      stateful: true

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05            # = 1 / controller_frequency
      batch_size: 2000
      vx_std: 0.2
      vy_std: 0.0                # diff drive has no lateral DOF
      wz_std: 0.4
      vx_max: 1.0
      vx_min: -0.5                # allow reversing - relevant given your rows are narrow and you've hit "can't reverse" issues with RPP before
      vy_max: 0.0
      wz_max: 1.0
      ax_max: 2.0
      ax_min: -2.0
      ay_max: 0.0
      ay_min: 0.0
      az_max: 3.0
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.5
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: false
      regenerate_noises: false

      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3

      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic",
                "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        near_goal_distance: 1.0

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0